CREATE DATABASE IF NOT EXISTS airline_db;
USE airline_db;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS SEAT;
DROP TABLE IF EXISTS CAN_LAND;
DROP TABLE IF EXISTS LEG_INSTANCE;
DROP TABLE IF EXISTS FARE;
DROP TABLE IF EXISTS FLIGHT_LEG;
DROP TABLE IF EXISTS FLIGHT;
DROP TABLE IF EXISTS AIRPLANE;
DROP TABLE IF EXISTS AIRPLANE_TYPE;
DROP TABLE IF EXISTS AIRPORT;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE AIRPLANE_TYPE (
    Type_name VARCHAR(10) NOT NULL,
    Company VARCHAR(100) NOT NULL,
    Max_seats INT NOT NULL,
    CONSTRAINT PK_AIRPLANE_TYPE PRIMARY KEY (Type_name)
);
CREATE TABLE AIRPORT (
    Airport_code CHAR(3) NOT NULL,
    Name VARCHAR(100) NOT NULL,
    City VARCHAR(50) NOT NULL,
    State VARCHAR(10) NOT NULL,
    CONSTRAINT PK_AIRPORT PRIMARY KEY (Airport_code)
);
CREATE TABLE AIRPLANE (
    Airplane_id VARCHAR(20) NOT NULL,
    Total_no_of_seats INT NOT NULL,
    Type_name VARCHAR(10) NOT NULL,
    CONSTRAINT PK_AIRPLANE PRIMARY KEY (Airplane_id),
    CONSTRAINT FK_AIRPLANE_TYPE FOREIGN KEY (Type_name)
    REFERENCES AIRPLANE_TYPE(Type_name)
    ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE FLIGHT (
    Number INT NOT NULL,
    Airline VARCHAR(50) NOT NULL,
    Weekdays VARCHAR(7) NOT NULL,
    CONSTRAINT PK_FLIGHT PRIMARY KEY (Number)
);
CREATE TABLE FLIGHT_LEG (
    Flight_number INT NOT NULL,
    Leg_no INT NOT NULL,
    Dep_airport_code CHAR(3) NOT NULL,
    Arr_airport_code CHAR(3) NOT NULL,
    Scheduled_dep_time TIME NOT NULL,
    Scheduled_arr_time TIME NOT NULL,
    CONSTRAINT PK_FLIGHT_LEG PRIMARY KEY (Flight_number, Leg_no),
    CONSTRAINT FK_FLIGHT_LEG_FLIGHT FOREIGN KEY (Flight_number)
    REFERENCES FLIGHT(Number)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_FLIGHT_LEG_DEP_AIRPORT FOREIGN KEY (Dep_airport_code)
    REFERENCES AIRPORT(Airport_code)
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_FLIGHT_LEG_ARR_AIRPORT FOREIGN KEY (Arr_airport_code)
    REFERENCES AIRPORT(Airport_code)
    ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE FARE (
    Flight_number INT NOT NULL,
    Code VARCHAR(20) NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
    Restrictions TEXT,
    CONSTRAINT PK_FARE PRIMARY KEY (Flight_number, Code),
    CONSTRAINT FK_FARE_FLIGHT FOREIGN KEY (Flight_number)
    REFERENCES FLIGHT(Number)
    ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE LEG_INSTANCE (
    Flight_number INT NOT NULL,
    Leg_no INT NOT NULL,
    Date DATE NOT NULL,
    No_of_avail_seats INT NOT NULL,
    Airplane_id VARCHAR(20) NOT NULL,

    Dep_time TIME,
    Arr_time TIME,
    CONSTRAINT PK_LEG_INSTANCE PRIMARY KEY (Flight_number, Leg_no, Date),
    CONSTRAINT FK_LEG_INSTANCE_FLIGHT_LEG FOREIGN KEY (Flight_number, Leg_no)
    REFERENCES FLIGHT_LEG(Flight_number, Leg_no)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_LEG_INSTANCE_AIRPLANE FOREIGN KEY (Airplane_id)
    REFERENCES AIRPLANE(Airplane_id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE SEAT (
    Airplane_id VARCHAR(20) NOT NULL,
    Seat_no VARCHAR(5) NOT NULL,
    Class VARCHAR(20),
    CONSTRAINT PK_SEAT PRIMARY KEY (Airplane_id, Seat_no),
    CONSTRAINT FK_SEAT_AIRPLANE FOREIGN KEY (Airplane_id)
    REFERENCES AIRPLANE(Airplane_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE CAN_LAND (
    Airport_code CHAR(3) NOT NULL,
    Type_name VARCHAR(10) NOT NULL,
    CONSTRAINT PK_CAN_LAND PRIMARY KEY (Airport_code, Type_name),
    CONSTRAINT FK_CAN_LAND_AIRPORT FOREIGN KEY (Airport_code)
    REFERENCES AIRPORT(Airport_code)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CAN_LAND_AIRPLANE_TYPE FOREIGN KEY (Type_name)
    REFERENCES AIRPLANE_TYPE(Type_name)
    ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE RESERVATION (
    Airplane_id VARCHAR(20) NOT NULL,
    Seat_no VARCHAR(5) NOT NULL,
    Flight_number INT NOT NULL,
    Leg_no INT NOT NULL,
    Date DATE NOT NULL,
    Customer_name VARCHAR(100) NOT NULL,
    Cphone VARCHAR(20),
    CONSTRAINT PK_RESERVATION PRIMARY KEY (Airplane_id, Seat_no, Flight_number, Leg_no, Date),
    CONSTRAINT FK_RESERVATION_SEAT FOREIGN KEY (Airplane_id, Seat_no)
    REFERENCES SEAT(Airplane_id, Seat_no)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_RESERVATION_LEG_INSTANCE FOREIGN KEY (Flight_number, Leg_no, Date)
    REFERENCES LEG_INSTANCE(Flight_number, Leg_no, Date)
    ON DELETE CASCADE ON UPDATE CASCADE
);
SET GLOBAL local_infile = 1;
LOAD DATA LOCAL INFILE 'Airport_System_Project/database//database/AIRPLANE_TYPE.csv'
INTO TABLE AIRPLANE_TYPE
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Type_name, Company, Max_seats);
LOAD DATA LOCAL INFILE 'Airport_System_Project/database//database/AIRPORT.csv'
INTO TABLE AIRPORT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Airport_code, Name, City, State);
LOAD DATA LOCAL INFILE 'Airport_System_Project/database//database/AIRPLANE.csv'
INTO TABLE AIRPLANE
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Airplane_id, Total_no_of_seats, Type_name);
LOAD DATA LOCAL INFILE 'Airport_System_Project/database//database/FLIGHT.csv'
INTO TABLE FLIGHT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Number, Airline, Weekdays);
LOAD DATA LOCAL INFILE 'Airport_System_Project/database/database/FLIGHT_LEG.csv'
INTO TABLE FLIGHT_LEG
FIELDS TERMINATED BY ','

OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Flight_number, Leg_no, Dep_airport_code, Arr_airport_code, Scheduled_dep_time, Scheduled_arr_time);
LOAD DATA LOCAL INFILE 'Airport_System_Project/database/FARE.csv'
INTO TABLE FARE
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Flight_number, Code, Amount, Restrictions);
LOAD DATA LOCAL INFILE 'Airport_System_Project/database/LEG_INSTANCE.csv'
INTO TABLE LEG_INSTANCE
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Flight_number, Leg_no, Date, No_of_avail_seats, Airplane_id, Dep_time, Arr_time);
LOAD DATA LOCAL INFILE 'Airport_System_Project/database/SEAT.csv'
INTO TABLE SEAT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Airplane_id, Seat_no, Class);
LOAD DATA LOCAL INFILE 'Airport_System_Project/database/CAN_LAND.csv'
INTO TABLE CAN_LAND
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Airport_code, Type_name);